name: kaldi_asr_platform_interface
description: A Flutter plugin for Kaldi ASR.
version: 1.0.2
homepage: https://github.com/nmfisher/kaldi_asr_ffi

dependencies:
  plugin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
